sudo: true
language: go

go:
- 1.6.2


services:

- docker

env:
  COMPOSE_VERSION: 1.7.1
 
before_install:
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin

install:

- docker-compose up -d

script:
- docker ps | grep -q haproxy
- go run tests/test.go http://localhost/
