author: bencane
comments: true
date: 2011-08-04 00:41:00+00:00
popularity: None
slug: bash-repeated-tasks-with-seq-and-for-loops-shell-fu
title: 'Bash: Repeated tasks with seq and for loops'
post_id: 24
categories:
- All Articles
- Command Line
- Programming
- Shell Scripting
tags:
- bash
- linux
- tech
- unix
file: 2011-08-04-bash-repeated-tasks-with-seq-and-for-loops-shell-fu.md
published: True
pubdate: Thu, 04 Aug 2011 00:00:00 +0000
