date: 2011-06-25 01:24:54+00:00
slug: setfacl-invalid-argument-near-character
title: 'setfacl: Invalid argument near character'
post_id: 2
categories:
- Administration
- Command Line
- Linux
- Linux Commands
tags:
- acl
- linux
- tech
popularity: None
file: 2011-06-25-setfacl-invalid-argument-near-character.md
published: True
pubdate: Sat, 25 Jun 2011 00:00:00 +0000
