author: bencane
comments: true
date: 2011-11-02 20:00:06+00:00
popularity: True
slug: did-my-cronjob-run
title: How to check if a cron job ran
description: This article shows a simple method to validate whether or not a cronjob ran on both Red Hat/Fedora based and Debian based Linux Systems
post_id: 58
categories:
- Administration
- Linux
- Linux Distributions
- Red Hat
- Troubleshooting
- Ubuntu
tags:
- config
- cron
- crond
- cronjob
- crons
- daemon
- debian
- fedora
- linux
- linux scheduled jobs
- linux scheduled tasks
- log message
- logs
- scheduled tasks
- tech
- ubuntu
- unix
- unix linux
file: 2011-11-02-did-my-cronjob-run.md
published: True
pubdate: Wed, 02 Nov 2011 00:00:00 +0000
