author: bencane
comments: true
date: 2011-08-06 02:20:00+00:00
popularity: None
slug: counting-with-sort-and-uniq-shell-fu
title: Counting with sort and uniq
post_id: 26
categories:
- Command Line
- Linux
- Linux Commands
- Unix
- Unix Commands
tags:
- linux
- tech
- unix
file: 2011-08-06-counting-with-sort-and-uniq-shell-fu.md
published: True
pubdate: Sat, 06 Aug 2011 00:00:00 +0000
