author: bencane
comments: true
date: 2011-08-12 20:30:06+00:00
popularity: None
slug: sar-system-statistics
title: 'sar: System statistics'
post_id: 31
categories:
- Command Line
- Linux
- Linux Commands
tags:
- linux
- sar
- tech
file: 2011-08-12-sar-system-statistics.md
published: True
pubdate: Fri, 12 Aug 2011 00:00:00 +0000
