author: bencane
comments: true
date: 2011-08-10 20:30:06+00:00
popularity: None
slug: runlevel-check-your-current-runlevel-then-change-it
title: 'runlevel: Check your current runlevel. Then change it'
post_id: 29
categories:
- Command Line
- Linux
- Linux Commands
tags:
- init
- inittab
- linux
- runlevel
- tech
file: 2011-08-10-runlevel-check-your-current-runlevel-then-change-it.md
published: True
pubdate: Wed, 10 Aug 2011 00:00:00 +0000
