author: bencane
comments: true
date: 2011-07-26 08:00:32+00:00
popularity: None
slug: tar-exclude-directoriesfiles-shell-fu
title: 'tar: Exclude directories/files'
post_id: 20
categories:
- Command Line
- Linux
- Linux Commands
- Unix
- Unix Commands
tags:
- linux
- tech
- unix
file: 2011-07-26-tar-exclude-directoriesfiles-shell-fu.md
published: True
pubdate: Tue, 26 Jul 2011 00:00:00 +0000
