author: bencane
comments: true
date: 2011-10-25 20:00:00+00:00
popularity: None
slug: dscacheutil-clearing-dns-cache-on-osx
title: 'dscacheutil: Clearing DNS cache on OSX'
post_id: 57
categories:
- Command Line
- OSX
- Unix
- Unix Distributions
tags:
- bash
- mac
- osx
- tech
file: 2011-10-25-dscacheutil-clearing-dns-cache-on-osx.md
published: True
pubdate: Tue, 25 Oct 2011 00:00:00 +0000
