author: bencane
comments: true
date: 2011-07-22 07:51:00+00:00
popularity: None
slug: rpm-finding-dependencies-shell-fu
title: 'rpm: Finding dependencies'
post_id: 17
categories:
- Command Line
- Linux
- Linux Commands
tags:
- linux
- redhat
- rpm
- tech
file: 2011-07-22-rpm-finding-dependencies-shell-fu.md
published: True
pubdate: Fri, 22 Jul 2011 00:00:00 +0000
