author: bencane
comments: true
date: 2011-08-14 20:30:05+00:00
popularity: None
slug: find-the-biggest-directories-with-du-cmd-of-the-day
title: Find the biggest directories with du
post_id: 33
categories:
- Administration
- All Articles
- Command Line
- Linux
- Linux Commands
- Unix
- Unix Commands
tags:
- linux
- tech
- unix
file: 2011-08-14-find-the-biggest-directories-with-du-cmd-of-the-day.md
published: True
pubdate: Sun, 14 Aug 2011 00:00:00 +0000
