author: bencane
comments: true
date: 2011-09-13 20:01:05+00:00
popularity: None
slug: find-yet-another-cool-find
title: 'find: Print type of file, inode #, filename and link destination'
post_id: 49
categories:
- All Articles
- Command Line
- Linux
- Linux Commands
- Unix
- Unix Commands
tags:
- linux
- tech
- unix
file: 2011-09-13-find-yet-another-cool-find.md
published: True
pubdate: Tue, 13 Sep 2011 00:00:00 +0000
