author: bencane
comments: true
date: 2011-08-08 20:00:05+00:00
popularity: None
slug: showmount-see-available-nfs-shares-cmd-of-the-day
title: 'showmount: See available NFS Shares'
post_id: 27
categories:
- Applications
- Command Line
- File Systems
- Linux
- Linux Commands
- NFS
- Unix
- Unix Commands
tags:
- bsd
- linux
- nfs
- tech
- unix
file: 2011-08-08-showmount-see-available-nfs-shares-cmd-of-the-day.md
published: True
pubdate: Mon, 08 Aug 2011 00:00:00 +0000
