author: bencane
comments: true
date: 2011-08-18 20:31:00+00:00
popularity: None
slug: find-remove-files-modified-more-than-31-days-ago
title: 'find: Remove files modified more than 31 days ago'
post_id: 37
categories:
- All Articles
- Command Line
- Linux
- Linux Commands
- Unix
- Unix Commands
tags:
- find
- linux
- tech
- unix
file: 2011-08-18-find-remove-files-modified-more-than-31-days-ago.md
published: True
pubdate: Thu, 18 Aug 2011 00:00:00 +0000
