author: bencane
comments: true
date: 2011-08-05 06:27:48+00:00
popularity: None
slug: filename-manipulation-with-sed-awk-and-cut-shell-fu
title: Filename manipulation with sed, awk and cut
post_id: 25
categories:
- Command Line
- Linux Commands
- Shell Scripting
- Unix Commands
tags:
- linux
- osx
- tech
- unix
file: 2011-08-05-filename-manipulation-with-sed-awk-and-cut-shell-fu.md
published: True
pubdate: Fri, 05 Aug 2011 00:00:00 +0000
