author: bencane
comments: true
date: 2011-07-16 02:43:59+00:00
popularity: None
slug: sudoers-syntax-checking-best-practices
title: 'sudoers: Syntax Checking'
post_id: 15
categories:
- Administration
- Best Practices
- Linux
- Linux Commands
- Security
- Unix
- Unix Commands
tags:
- linux
- tech
- unix
file: 2011-07-16-sudoers-syntax-checking-best-practices.md
published: True
pubdate: Sat, 16 Jul 2011 00:00:00 +0000
