author: bencane
comments: true
date: 2011-08-09 20:30:05+00:00
popularity: None
slug: ssh-x11-forwarding-cmd-of-the-day
title: 'ssh: X11 Forwarding'
post_id: 28
categories:
- Command Line
- Linux
- Linux Commands
- Unix
- Unix Commands
tags:
- linux
- ssh
- tech
- x11
file: 2011-08-09-ssh-x11-forwarding-cmd-of-the-day.md
published: True
pubdate: Tue, 09 Aug 2011 00:00:00 +0000
