author: bencane
comments: true
date: 2011-08-27 05:47:00+00:00
popularity: None
slug: dpkg-listing-installed-packages
title: 'dpkg: Listing installed packages'
post_id: 43
categories:
- All Articles
- Command Line
- Linux
- Linux Commands
- Linux Distributions
- Ubuntu
tags:
- debian
- linux
- tech
file: 2011-08-27-dpkg-listing-installed-packages.md
published: True
pubdate: Sat, 27 Aug 2011 00:00:00 +0000
