author: bencane
comments: true
date: 2011-08-03 07:05:00+00:00
popularity: None
slug: finding-what-installed-a-binary-with-yum-and-rpm
title: Finding what installed a binary with YUM and RPM
thumbnail: http://bencane.com/img/thumbnails/yum.png
post_id: 22
categories:
- Command Line
- Linux
- Linux Commands
- Unix
- Unix Commands
tags:
- linux
- redhat
- rpm
- tech
- yum
file: 2011-08-03-finding-what-installed-a-binary-with-yum-and-rpm.md
published: True
pubdate: Wed, 03 Aug 2011 00:00:00 +0000
