author: bencane
comments: true
date: 2011-08-17 20:32:06+00:00
popularity: None
slug: sudo-list-available-commands
title: 'Sudo: List available commands'
post_id: 36
categories:
- All Articles
- Command Line
- Linux
- Linux Commands
- Unix
- Unix Commands
tags:
- linux
- sudo
- tech
- unix
file: 2011-08-17-sudo-list-available-commands.md
published: True
pubdate: Wed, 17 Aug 2011 00:00:00 +0000
