author: bencane
comments: true
date: 2011-07-14 21:00:06+00:00
popularity: None
slug: createextract-a-tar-file-using-contents-of-a-file-shell-fu
title: Create/Extract a tar file using contents of a file
post_id: 12
categories:
- Command Line
- Linux
- Linux Commands
- Unix
- Unix Commands
tags:
- linux
- tech
- unix
file: 2011-07-14-createextract-a-tar-file-using-contents-of-a-file-shell-fu.md
published: True
pubdate: Thu, 14 Jul 2011 00:00:00 +0000
