author: bencane
comments: true
date: 2011-12-26 16:00:21+00:00
popularity: None
slug: mysql-tee-saving-your-output-to-a-file
title: 'MySQL: tee saving your output to a file'
description: Learn to use the MySQL tee command to save the MySQL CLI output to a file and to your tty
thumbnail: http://bencane.com/img/thumbnails/mysql.jpg
post_id: 61
categories:
- Applications
- Command Line
- Databases
- MySQL
tags:
- linkedin
- linux
- mysql
- mysql cli
- tech
- tee
- unix
file: 2011-12-26-mysql-tee-saving-your-output-to-a-file.md
published: True
pubdate: Mon, 26 Dec 2011 00:00:00 +0000
