author: bencane
comments: true
date: 2011-07-23 07:00:00+00:00
popularity: None
slug: checking-your-running-kernel-version-quick-tip
title: Checking your running kernel version
post_id: 19
categories:
- Administration
- Command Line
- Linux
- Linux Commands
tags:
- apple
- kernel
- linux
- tech
- unix
file: 2011-07-23-checking-your-running-kernel-version-quick-tip.md
published: True
pubdate: Sat, 23 Jul 2011 00:00:00 +0000
