author: bencane
comments: true
date: 2011-12-30 09:30:25+00:00
popularity: True
slug: when-its-ok-and-not-ok-to-use-rc-local
title: When it's Ok and Not Ok to use rc.local
description: An article that discusses when it is appropriate and when it is not appropriate to use the rc.local file. A file that has been depreciated in some Linux distributions.
post_id: 62
categories:
- Administration
- Best Practices
- FreeBSD
- Linux
- Unix
- Unix Distributions
tags:
- bsd
- debian
- freebsd
- init
- linkedin
- linux
- linux os
- linux server
- os x
- rc auto
- red hat linux
- solaris
- System V
- tech
- unix
file: 2011-12-30-when-its-ok-and-not-ok-to-use-rc-local.md
published: True
pubdate: Fri, 30 Dec 2011 00:00:00 +0000
