author: bencane
comments: true
date: 2011-08-20 20:32:05+00:00
popularity: None
slug: sudo-running-as-a-specific-user
title: 'Sudo: Running as a specific user'
post_id: 39
categories:
- Administration
- All Articles
- Command Line
- Linux
- Linux Commands
- Security
- Unix
- Unix Commands
tags:
- linux
- sudo
- tech
- unix
file: 2011-08-20-sudo-running-as-a-specific-user.md
published: True
pubdate: Sat, 20 Aug 2011 00:00:00 +0000
