author: bencane
comments: true
date: 2011-08-24 20:32:05+00:00
popularity: None
slug: apt-searching-for-packages
title: 'apt: Searching for packages'
post_id: 41
categories:
- All Articles
- Command Line
- Linux
- Linux Distributions
- Ubuntu
tags:
- apt
- debian
- linux
- tech
file: 2011-08-24-apt-searching-for-packages.md
published: True
pubdate: Wed, 24 Aug 2011 00:00:00 +0000
