author: bencane
comments: true
date: 2011-07-01 02:11:00+00:00
popularity: None
slug: do-symlinks-use-up-inodes
title: Do Symlinks use up Inodes?
post_id: 6
categories:
- Administration
- Linux
tags:
- linux
- tech
- unix
file: 2011-07-01-do-symlinks-use-up-inodes.md
published: True
pubdate: Fri, 01 Jul 2011 00:00:00 +0000
