author: bencane
comments: true
date: 2011-08-15 20:30:00+00:00
popularity: None
slug: find-print-size-modify-date-type-and-filename
title: 'Find: Print Size, Modify Date, Type, and Filename'
post_id: 34
categories:
- Command Line
- Linux
- Linux Commands
- Unix
- Unix Commands
tags:
- linux
- tech
- unix
file: 2011-08-15-find-print-size-modify-date-type-and-filename.md
published: True
pubdate: Mon, 15 Aug 2011 00:00:00 +0000
