author: bencane
comments: true
date: 2011-07-22 08:21:00+00:00
popularity: None
slug: truncating-a-large-log-file-best-practices
title: Truncating a large log file
post_id: 18
categories:
- Administration
- All Articles
- Best Practices
- Command Line
- Linux
- Linux Commands
- Unix
- Unix Commands
tags:
- apple
- linux
- max osx
- osx
- tech
- unix
file: 2011-07-22-truncating-a-large-log-file-best-practices.md
published: True
pubdate: Fri, 22 Jul 2011 00:00:00 +0000
