author: bencane
comments: true
date: 2012-07-22 16:54:23+00:00
popularity: None
slug: cheat-sheet-21-useful-find-commands
title: 'Cheat Sheet: 21 useful find commands'
post_id: 74
categories:
- All Articles
- Cheat Sheets
- Command Line
- Linux
- Linux Commands
- Unix
- Unix Commands
tags:
- apple
- debian
- exec
- executable files
- find
- gnu
- inode
- linkedin
- linux
- linux os
- mac osx
- redhat
- sudo
- suid
- suid files
- tech
- ubuntu
- unix
file: 2012-07-22-cheat-sheet-21-useful-find-commands.md
published: True
pubdate: Sun, 22 Jul 2012 00:00:00 +0000
