author: bencane
comments: true
date: 2012-01-19 15:20:54+00:00
popularity: True
slug: cheat-sheet-systemctl-vs-chkconfig
title: 'Cheat Sheet: systemctl vs chkconfig'
description: A simple cheat sheet that shows how to perform the same task with both systemctl and chkconfig
post_id: 63
categories:
- Cheat Sheets
- Linux
- Linux Commands
- Linux Distributions
- Red Hat
tags:
- chkconfig
- linkedin
- linux
- systemctl
- systemd
- tech
file: 2012-01-19-cheat-sheet-systemctl-vs-chkconfig.md
published: True
pubdate: Thu, 19 Jan 2012 00:00:00 +0000
