author: bencane
comments: true
date: 2012-04-01 19:28:31+00:00
popularity: None
slug: sysadmin-tools-managing-linux-from-a-windows-desktop
title: 'Sysadmin Tools: Managing Linux from a Windows Desktop'
post_id: 67
categories:
- Administration
- All Articles
- Linux
- Unix
tags:
- fedora
- linkedin
- linux
- oracle
- PuTTY
- ssh
- tech
- ubuntu
- unix
- vdi
- virtualbox
- windows
- Windows Tools
file: 2012-04-01-sysadmin-tools-managing-linux-from-a-windows-desktop.md
published: True
pubdate: Sun, 01 Apr 2012 00:00:00 +0000
