author: bencane
comments: true
date: 2012-03-24 19:33:45+00:00
popularity: None
slug: advanced-linux-troubleshooting-strace
title: Linux Troubleshooting with strace
post_id: 66
categories:
- Administration
- All Articles
- Linux
- Linux Commands
- Troubleshooting
tags:
- kernel
- linkedin
- linux
- redhat
- strace
- tech
- troubleshooting
- troubleshooting linux
- unix
file: 2012-03-24-advanced-linux-troubleshooting-strace.md
published: True
pubdate: Sat, 24 Mar 2012 00:00:00 +0000
