author: bencane
comments: true
date: 2012-10-22 16:30:01+00:00
popularity: None
slug: cheat-sheet-cutting-text-with-cut
title: 'Cheat Sheet: Cutting Text with cut'
post_id: 80
categories:
- All Articles
- Command Line
- Linux
- Linux Commands
- Unix
- Unix Commands
tags:
- all
- awk
- bash
- csv file
- cut
- gnu linux
- linux
- ubuntu
- unix
file: 2012-10-22-cheat-sheet-cutting-text-with-cut.md
published: True
pubdate: Mon, 22 Oct 2012 00:00:00 +0000
