author: bencane
comments: true
date: 2012-02-20 15:24:29+00:00
popularity: None
slug: why-you-should-avoid-running-applications-as-root
title: Why you should avoid running applications as root
post_id: 64
categories:
- Administration
- All Articles
- Best Practices
- Linux
- Security
- Unix
tags:
- apache
- bsd
- debian
- linux
- nginx
- security
- sudo
- suid
- tech
- unix
file: 2012-02-20-why-you-should-avoid-running-applications-as-root.md
published: True
pubdate: Mon, 20 Feb 2012 00:00:00 +0000
