author: bencane
comments: true
date: 2012-05-24 15:46:31+00:00
popularity: None
slug: stat-detailed-information-about-a-file
title: 'Stat: Detailed information about a file'
post_id: 69
categories:
- All Articles
- Command Line
- Linux
- Linux Commands
tags:
- filesystems
- hardlinks
- inode
- linux
- stat
- tech
- unix
file: 2012-05-24-stat-detailed-information-about-a-file.md
published: True
pubdate: Thu, 24 May 2012 00:00:00 +0000
