author: bencane
comments: true
date: 2012-08-13 11:30:38+00:00
popularity: None
slug: xargs-build-and-execute-commands-with-arguments-from-standard-input
title: 'xargs: Build and Execute Commands with Arguments from Standard Input'
post_id: 76
categories:
- All Articles
- Command Line
- Linux
- Linux Commands
- Unix
- Unix Commands
tags:
- bash
- chmod command
- examples of xargs
- exec
- find
- gnu
- gnu linux
- gnu xargs
- i/o
- linkedin
- linux
- process
- shell
- stdin
- unix
- xargs
- xargs examples
file: 2012-08-13-xargs-build-and-execute-commands-with-arguments-from-standard-input.md
published: True
pubdate: Mon, 13 Aug 2012 00:00:00 +0000
