author: bencane
comments: true
date: 2013-01-14 13:15:03+00:00
popularity: True
slug: mitigating-dos-attacks-with-a-null-or-blackhole-route-on-linux
title: Mitigating DoS Attacks with a null (or Blackhole) Route on Linux
description: A guide on how to lessen the damage of a DoS attack by using a null route in Linux
post_id: 83
categories:
- Administration
- Best Practices
- Linux
- Linux Commands
- Networking
- Security
tags:
- black hole
- ddos attacks
- denial of service
- denial of service attacks
- firewall
- ip route
- iptables
- linux
- linux firewall
- network
- network communication
- null route
- route
- routing table
- tech
- unix
file: 2013-01-14-mitigating-dos-attacks-with-a-null-or-blackhole-route-on-linux.md
published: True
pubdate: Mon, 14 Jan 2013 00:00:00 +0000
