author: bencane
comments: true
date: 2013-08-19 08:00:43+00:00
popularity: None
slug: grepping-a-file-without-using-cat-and-grep-other-tricks
title: Grepping a file without using cat, and other grep tricks
description: A lot of sysadmins don't realize you can use grep without cat, this article should settle that. It also shows some other grep tricks.
post_id: 97
categories:
- All Articles
- Command Line
- Linux
- Linux Commands
- Programming
- Shell Scripting
- SysAdmin Basics
- Unix
- Unix Commands
tags:
- bash
- grep
- grep -v
- linux
- linux os
- red hat os
- shell best practices
- shell scripting
file: 2013-08-19-grepping-a-file-without-using-cat-and-grep-other-tricks.md
published: True
pubdate: Mon, 19 Aug 2013 00:00:00 +0000
