author: bencane
comments: true
date: 2013-04-22 23:50:22+00:00
popularity: None
slug: websphere-mq-cheat-sheet-for-system-administrators
title: Websphere MQ Cheat Sheet for System Administrators
description: A simple cheat sheet that shows commands every sysadmin managing WebSphere MQ could use
post_id: 87
categories:
- All Articles
- Applications
- Cheat Sheets
- Linux
- Linux Commands
- Middleware
- WebSphere MQ
tags:
- ibm
- linkedin
- linux
- listener
- mq
- queue manager
- scripts
- system administrators
- websphere mq
- websphere mq cheat sheet
file: 2013-04-22-websphere-mq-cheat-sheet-for-system-administrators.md
published: True
pubdate: Mon, 22 Apr 2013 00:00:00 +0000
