author: bencane
comments: true
date: 2013-05-23 15:07:37+00:00
popularity: None
slug: packing-and-unpacking-files-with-gnu-tar
title: Packing and Unpacking files with GNU Tar
description: Simple guide on using a basic Unix and Linux tool GNU tar
post_id: 91
categories:
- Command Line
- Linux
- Linux Commands
- SysAdmin Basics
- Unix
- Unix Commands
tags:
- all
- extracting a tar file
- linux
- linux os
- red hat os
- tar command
- tarcopy
- tarpipe
file: 2013-05-23-packing-and-unpacking-files-with-gnu-tar.md
published: True
pubdate: Thu, 23 May 2013 00:00:00 +0000
