author: bencane
comments: true
date: 2013-06-05 01:55:38+00:00
popularity: None
slug: emc-powerpath-superblock-could-not-be-read
title: 'EMC PowerPath: superblock could not be read'
description: How to get around a simple setup issue where fsck tries to check a SAN disk before EMC PowerPath starts 
post_id: 92
categories:
- All Articles
- Linux
- Red Hat
- Troubleshooting
tags:
- emc powerpath
- filesystems
- fsck
- linux os
- red hat
- red hat os
- superblock
file: 2013-06-05-emc-powerpath-superblock-could-not-be-read.md
published: True
pubdate: Wed, 05 Jun 2013 00:00:00 +0000
