author: madflojo
date: 2013-12-23 08:00:00+00:00
pubdate: Mon, 23 Dec 2013 08:00:00 +00:00
popularity: None
slug: yum-plugins-verifying-packages-and-configurations-with-yum-verify
title: "Yum Plugins: Verifying packages and configurations with Yum Verify"
description: An introduction to Yum Plugins and Yum Verify
post_id: 110
categories:
- Linux
- Yum
- Red Hat
tags:
- linux
- redhat
- yum
- yum plugins
- centos
- package manager
- yellowdog update manager
file: 2013-12-23-yum-plugins-verifying-packages-and-configurations-with-yum-verify.md
published: True
