author: bencane
comments: true
date: 2013-10-21 08:15:26+00:00
popularity: True
slug: 5-bash-for-loop-examples-to-make-command-line-tasks-more-efficient
title: 5 Bash for loop examples to make command line tasks more efficient
description: Examples of bash for loops that can make any shell users life easier
post_id: 107
categories:
- Command Line
- Linux
- Linux Commands
- Programming
- Shell Scripting
- SysAdmin Basics
- Unix
- Unix Commands
tags:
- bash
- cut
- gnu linux
- grep
- home directories
- linux tutorial
- scripting
- scripts
- shell
- shell commands
- shell scripting
- unix and linux
- unix linux
file: 2013-10-21-5-bash-for-loop-examples-to-make-command-line-tasks-more-efficient.md
published: True
pubdate: Mon, 21 Oct 2013 00:00:00 +0000
