author: bencane
comments: true
date: 2013-08-26 06:00:40+00:00
popularity: None
slug: reading-files-in-reverse-with-tac
title: Reading files in reverse with tac
description: A cool trick that shows how to read files in reverse with the tac command
post_id: 98
categories:
- All Articles
- Command Line
- Linux
- Linux Commands
- Shell Scripting
- SysAdmin Basics
tags:
- bash
- cat
- gnu linux
- linux
- linux os
- red hat os
- scripting
- shell commands
- sort
- tac
file: 2013-08-26-reading-files-in-reverse-with-tac.md
published: True
pubdate: Mon, 26 Aug 2013 00:00:00 +0000
