author: bencane
comments: true
date: 2013-05-13 04:16:25+00:00
popularity: None
slug: removing-files-and-directories-with-rm-and-rmdir
title: Removing Files and Directories with rm and rmdir
description: A simple guide on using rm and rmdir some of the basic Shell commands in Linux and Unix environments
post_id: 89
categories:
- Cheat Sheets
- Command Line
- Linux
- Linux Commands
- SysAdmin Basics
- Unix
- Unix Commands
tags:
- bash
- empty directories
- linux
- rm command
- rmdir command
- sysadmin
- unix
- learn linux
file: 2013-05-13-removing-files-and-directories-with-rm-and-rmdir.md
published: True
pubdate: Mon, 13 May 2013 00:00:00 +0000
