author: bencane
comments: true
date: 2013-06-12 12:39:19+00:00
popularity: None
slug: mkisofs-repackaging-a-linux-install-iso
title: 'mkisofs: Repackaging a Linux Install ISO'
description: Repackaging a Linux installation DVD using mkisofs
post_id: 94
categories:
- All Articles
- Command Line
- Linux
- Linux Commands
tags:
- all
- iso file
- isolinux
- linux
- linux os
- mkisofs
- red hat
- red hat os
file: 2013-06-12-mkisofs-repackaging-a-linux-install-iso.md
published: True
pubdate: Wed, 12 Jun 2013 00:00:00 +0000
