author: madflojo
date: 2014-04-01 08:55:00+00:00
pubdate: Tue, 01 Apr 2014 08:55:00 +00:00
popularity: None
slug: understanding-the-kill-command-and-how-to-terminate-processes-in-linux
title: "Understanding the kill command, and how to terminate processes in Linux"
description: This article covers the Linux kill command and how it sends signals to terminate processes. Also why you should avoid using kill -9.
post_id: 117
categories:
- Linux
tags:
- linux
- redhat
- centos
- ubuntu
- signal
- kill
- linux kill
- kill processes
- killall
- linux processes
- sigkill
- sigterm
- sigquit
- sighup
file: 2014-04-01-stopping-a-process-with-kill-and-linux-signal.md
published: True
