author: madflojo
date: 2014-08-18 07:45:00-07:00
pubdate: Mon, 18 Aug 2014 07:45:00 -07:00
popularity: None
slug: removing-packages-and-configurations-with-apt-get
title: "Removing packages and configurations with apt-get"
description: Removing an installed package with apt-get isn't as straight forward as you would think. This article walks you through removing a package the right way to allow for re-installation later and how to fix when an install will not deploy configuration files.
post_id: 122
categories:
- Linux
tags:
- linux
- debian
- ubuntu
- apt-get
- apt
- package managers
- installing packages
- apt-get configuration files
file: 2014-08-18-removing-packages-and-configurations-with-apt-get.md
published: True
