author: madflojo
date: 2014-03-05 08:30:00+00:00
pubdate: Wed, 05 Mar 2014 08:30:00 +00:00
popularity: None
slug: getting-around-the-linux-directory-structure-with-the-cd-command
title: "Getting around the Linux directory structure with the cd command"
description: An overview of the Linux directory structure and how to move around it with the cd command.
post_id: 116
categories:
- Linux Basics
- Shell
tags:
- linux
- redhat
- centos
- bash
- linux shell
- unix shell
- linux directory structure
- linux directories
- linux cd
- linux pwd
file: 2014-03-05-getting-around-the-linux-directory-structure-with-the-cd-command.md
published: True
