author: madflojo
date: 2014-04-18 09:30:00+00:00
pubdate: Fri, 18 Apr 2014 09:30:00 +00:00
popularity: True
slug: using-sysdig-to-troubleshoot-like-a-boss
title: "Using sysdig to Troubleshoot like a boss"
description: An introduction to sysdig, a new tool for advanced system troubleshooting.
post_id: 118
categories:
- Linux
- Troubleshooting
tags:
- linux
- sysdig
- systemtap
- dtrace
- strace
file: 2014-04-15-using-sysdig-to-troubleshoot-like-a-boss.md
published: True
