author: Benjamin Cane
date: 2014-01-07 08:00:00+00:00
pubdate: Tue, 07 Jan 2014 08:00:00 +00:00
popularity: None
slug: using-rsync-to-synchronize-a-local-and-remote-directory
title: "Using rsync to synchronize a local and remote directory"
description: An introduction to rsync and instructions on how to setup an automated rsync copy between two hosts
post_id: 111
categories:
- Linux
- rsync
tags:
- linux
- redhat
- rsync
- centos
- ubuntu
- debian
- linux copy files
- copy large files in linux
file: 2014-01-07-using-rsync-to-synchronize-a-local-and-remote-directory.md
published: True
