author: madflojo
date: 2014-06-06 07:00:00+00:00
pubdate: Fri, 06 Jun 2014 07:00:00 -07:00
popularity: True
slug: 8-tips-for-creating-better-bash-scripts
title: "8 Tips for creating better bash scripts"
description: This article covers some simple bash scripting best practices that can be used to improve the quality of your shell scripts.
post_id: 120
categories:
- Bash Scripting
tags:
- linux
- unix
- bash
- bash scripts
- bash best practices
- shell scripting
- linux shell scripts
- linux scripting
file: 2014-06-06-8-tips-for-creating-better-bash-scripts.md
published: True
