author: madflojo
date: 2015-09-22 06:20:00-07:00
pubdate: Tue, 22 Sep 2015 06:20:00 -07:00
popularity: False
slug: preventing-duplicate-cron-job-executions
title: "Preventing duplicate cron job executions"
description: "This article will show both BASH code and utilities that can be used to prevent a cron job from having multiple running instances"
post_id: 126
categories:
- Bash Scripting
- Cron jobs
tags:
- bash
- shell scripting
- cron
- cronjob
- cron jobs
- scheduling
- duplicate scripts
- sh
- shell
- scripting
- cron scripts
- lock file
- pid file
- pidfile
- flock
file: 2015-09-22-preventing-duplicate-cron-job-executions.md
published: True
